version: 2
jobs:
  test:
    docker:
      - image: circleci/node:9.2.0
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run: docker info
      - run:
          name: testing
          command: docker-compose -f docker-compose-test.yml run docker-cicd
  deploy:
#    machine: ture
    docker:
      - image: circleci/node:9.2.0
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: install EB command line
          command: >
            sudo apt-get update &&
            sudo pip install -y python python-dev python-pip
            python-virtualenv &&
            sudo pip install --update --user awsebcli
      - run:
          name: setup eb credential
          command: >
            mkdir -p ~/.aws &&
            echo [default] >> ~/.aws/credentials &&
            echo aws_access_key_id = $AWS_ACCESS_KEY_ID >> ~/.aws/credentials &&
            echo aws_secret_access_key = $AWS_SECRET_ACCESS_KEY >>  ~/.aws/credentials &&



      - deploy:
          nanme: deploy to aws eb
          command: sudo eb deploy env-dev
workflows:
  version: 2
  docker-cicd:
    jobs:
      - test
      - deploy:
          requires:
            - test
